#! python
# -*- coding: utf-8 -*-
#
# SEMulator3D Optimized Virtual Fabrication Build Script
# -------------------------------------------------------
# Autogenerated by Coventor SEMulator3D on 8/28/2026
# SEMulator3D version: 13.1
#
# Purpose:
#   Runs the full 22 nm 6T FinFET SRAM virtual fabrication for the
#   OPTIMIZED layout (6TSRAM_OPTI_1.gds). This script reproduces the
#   3-D structural model for the 18% area-reduced bitcell in SEMulator3D.
#
# Key difference from baseline:
#   - Layout file: 6TSRAM_OPTI_1.gds (X-direction scaled by 0.82)
#   - Cell: 1121.76 × 584 nm  |  Area: 655,107.84 nm²  |  18% reduction
#
# Inputs:
#   - Layout (GDS):   layout/optimized/optimized_6t_sram_finfet_18pct.gds
#   - Process file:   process/finfet_22nm.vproc      (same as baseline)
#   - Analysis file:  process/finfet_analysis.vanalysis
#   - Material file:  process/finfet_22nm_materials.vmpd
#   - Assembly file:  (provide a .zam output path; not committed to VCS)
#
# Usage (after updating file paths below):
#   python semulator3d_optimized_build.py
#
# Requirements:
#   - Coventor SEMulator3D 13.1 installation
#   - SEMulator3D Python API
#   - Valid SEMulator3D license
#
# NOTE: File paths below are from the original build machine.
#   Update all absolute paths to match your local environment before running.
# -------------------------------------------------------

import sys
import getopt
from voxelDocument import MonitorKillFile

opts, args = getopt.getopt(sys.argv[1:], '', ["fpw=", "mpw=", "spw=", "encrypted", "killFile="])

fpw, mpw, spw = '', '', ''
encrypted = False
for opt, arg in opts:
    if opt == "--fpw":
        fpw = arg
    elif opt == "--mpw":
        mpw = arg
    elif opt == "--spw":
        spw = arg
    elif opt == "--encrypted":
        encrypted = True
    elif opt == "--killFile":
        MonitorKillFile(arg)

_SEMulator3D_API_VERSION = '13.1'

import math
import time
import traceback
import logging

from voxelModeler import *

from CModeler import mpiInitialize
from CModeler import mpiFinalize
from subprocess import Popen
import sys
mpiInitialize(len(sys.argv), sys.argv)

_log = logging.getLogger("cov.modelBuilding")
startTime = time.time()

# ==============================================================
# Setup Masks
# Update these paths to match your local file locations
# ==============================================================
layoutFile = 'E:/6T_SRAM_Opt/FinFET-Input/6TSRAM_OPTI_1.gds'   # → layout/optimized/optimized_6t_sram_finfet_18pct.gds
layoutTopCell = 'Top'

# GDS layer map (same as baseline; matches layout/optimized/layermap.txt)
layerMap = {}
layerMap['Active']    = (5,   0)
layerMap['BB1']       = (6,   0)
layerMap['BB2']       = (33,  0)
layerMap['BB3']       = (34,  0)
layerMap['BB4']       = (130, 0)
layerMap['Fin']       = (0,   0)
layerMap['GateCut']   = (9,   0)
layerMap['GateUncut'] = (8,   0)
layerMap['LI']        = (17,  0)
layerMap['M1']        = (12,  0)
layerMap['M2']        = (14,  0)
layerMap['M2_L1']     = (29,  0)
layerMap['M2_L2']     = (30,  0)
layerMap['NWell']     = (2,   0)
layerMap['V0']        = (20,  0)
layerMap['V1']        = (13,  0)

# ==============================================================
# Setup Modeler
# ==============================================================
modelResolution = 1       # 1 nm voxel resolution
modelUnits = 'nm'

voxDoc = VoxelDocument('E:/6T_SRAM_Opt/FinFET.zam', modelResolution, modelUnits, LOAD)

modeler = VoxelModeler(voxDoc)

activeLayoutMaskNames = (
    'Active', 'BB2', 'Fin', 'GateCut', 'GateUncut', 'LI', 'M1', 'M2',
    'M2_E1_Gen', 'M2_E2_Gen', 'M2_L1', 'M2_L2', 'NWell', 'V0', 'V1',
    'V1_GROW', 'V1_Mask',
)
maskFile = MaskFile(layoutFile, layoutTopCell)
modeler.SetDefaultMaskUnitsPerMicron(maskFile.GetUnitsPerMicron())

for maskName in activeLayoutMaskNames:
    if maskName in layerMap.keys():
        mask = maskFile.GetLayerWithDataType(layerMap[maskName][0], layerMap[maskName][1])
        mask.SetName(maskName)
        modeler.AddActiveMask(mask)

modeler.CacheBuildBoundary()

# ==============================================================
# Load Process / Analysis / Materials
# Update paths to match your local environment
# ==============================================================
procDoc = CProcessData.ProcessDocument()
procDoc.openWithPasswords('E:/6T_SRAM_Opt/FinFET-Input/FinFET.vproc', fpw, mpw, encrypted)

analysisDoc = CProcessData.AnalysisDocument()
analysisDoc.openWithPasswords('E:/6T_SRAM_Opt/FinFET-Input/finFET.vanalysis', fpw, mpw, encrypted)

matDoc = CMaterialData.MaterialDocument()
matDoc.openWithPasswords('E:/6T_SRAM_Opt/FinFET-Input/FinFET.vmpd', fpw, mpw, encrypted)

for mat in matDoc.getActiveMaterialsInProcess(procDoc):
    voxDoc.GetMaterials().Add(mat, DUP_ADD_ALLOW)
for dopant in matDoc.getActiveDopantsInProcess(procDoc):
    voxDoc.GetDopants().Add(dopant, DUP_ADD_ALLOW)

if analysisDoc:
    for mat in matDoc.getActiveMaterialsInProcess(analysisDoc):
        voxDoc.GetMaterials().Add(mat, DUP_ADD_ALLOW)
    for dopant in matDoc.getActiveDopantsInProcess(analysisDoc):
        voxDoc.GetDopants().Add(dopant, DUP_ADD_ALLOW)

# ==============================================================
# Build Model
# ==============================================================
success = modeler.BuildModel(procDoc, analysisDoc, spw)

if not voxDoc.IsOutputEnabled():
    modeler.SaveFinalStep()

voxDoc.GetProperties().SetModelBuildComplete(success)
voxDoc.Save()

endTime = time.time()
_log.info('Build process completed.')
_log.info('Elapsed Time %d seconds.', (endTime - startTime))
mpiFinalize()

if voxDoc.GetProperties().GetStartViewer():
    Popen(['SEMulator3DViewer', 'E:/6T_SRAM_Opt/FinFET.zam', '-standalone:false'], env=os.environ)

if not success:
    sys.exit(1)
